name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    - name: Install dependencies
      run: pnpm install

    - name: Lint and fix files
      run: pnpm lintfix

    - name: Lint files
      run: pnpm lint

    - name: Build
      run: pnpm build